CREATE TABLE Endereco (
 IDEndereco VARCHAR(10) NOT NULL,
 Rua VARCHAR(60) NOT NULL,
 Estado CHAR(2) NOT NULL,
 Cidade VARCHAR(120) NOT NULL,
 Bairro VARCHAR(120) NOT NULL,
 Numero NUMERIC(10) NOT NULL,
 Complemento VARCHAR(120),
 CEP CHAR(8) NOT NULL
);

ALTER TABLE Endereco ADD CONSTRAINT PK_Endereco PRIMARY KEY (IDEndereco);


CREATE TABLE Profile (
 CPF CHAR(11) NOT NULL,
 Nome VARCHAR(120) NOT NULL,
 PedidosCompletos NUMERIC(10) DEFAULT 0 NOT NULL,
 Pontualidade NUMERIC(2) DEFAULT 10 NOT NULL,
 Sobre VARCHAR(200),
 IDFoto CHAR(11) DEFAULT '00000000000' NOT NULL
);

ALTER TABLE Profile ADD CONSTRAINT PK_Profile PRIMARY KEY (CPF);


CREATE TABLE Pedido (
 IDPedido VARCHAR(10) NOT NULL,
 CPFContratante CHAR(11) NOT NULL,
 ValorPago DOUBLE PRECISION NOT NULL,
 Descricao VARCHAR(200),
 Telefone VARCHAR(20) NOT NULL,
 Prazo DATE NOT NULL,
 CPFContratado CHAR(11),
 Status VARCHAR(120),
 IDEndereco VARCHAR(10) NOT NULL
);

ALTER TABLE Pedido ADD CONSTRAINT PK_Pedido PRIMARY KEY (IDPedido,CPFContratante);


ALTER TABLE Pedido ADD CONSTRAINT FK_Contratante FOREIGN KEY (CPFContratante) REFERENCES Profile (CPF);
ALTER TABLE Pedido ADD CONSTRAINT FK_Contratado FOREIGN KEY (CPFContratado) REFERENCES Profile (CPF);
ALTER TABLE Pedido ADD CONSTRAINT FK_Endereco FOREIGN KEY (IDEndereco) REFERENCES Endereco (IDEndereco);

ALTER TABLE Pedido MODIFY COLUMN IDPedido INT AUTO_INCREMENT

